Repository Owez/yark, pull requests merged in 2023-01, with the labels that each got.

#38 Metadata/download skipping and thumbnail fix
  templates/channel.html
  templates/video.html
  yark.py
Labels: enhancement

#39 Fixed broken video search in viewer
  yark.py
Labels: bug

#42 Interesting channel changes reporter
  yark.py
Labels: enhancement

#44 Polish README for 1.2 release and beyond
  README.md
  examples/images/channel.png
  examples/images/cli_dark.png
  examples/images/history.png
  examples/images/report.png
  examples/images/viewer_light.png
  examples/images/viewer_stats_light.png
Labels: documentation, enhancement

#43 Split files up for resturcture
  README.md
  examples/madness.py
  poetry.lock
  pyproject.toml
  yark.py
  yark/__init__.py
  yark/channel.py
  yark/cli.py
  yark/errors.py
  yark/reporter.py
  yark/templates/base.html
  yark/templates/channel.html
  yark/templates/index.html
  yark/templates/video.html
  yark/utils.py
  yark/video.py
  yark/viewer.py
Labels: documentation, enhancement

#46 Add channel-specific link on navbar
  examples/images/viewer_light.png
  yark/__main__.py
  yark/templates/base.html
Labels: enhancement, good first issue

#48 Moved commit to be 1 always at end
  yark/cli.py
Labels: bug, enhancement

#62 Skip pending livestream metadata fetching
  yark/channel.py
Labels: bug

#64 Type protection with mypy
  examples/madness.py
  poetry.lock
  pyproject.toml
  yark/__main__.py
  yark/channel.py
  yark/reporter.py
  yark/video.py
Labels: enhancement

#66 Undownloadable format warnings and faster thumbnail streaming
  README.md
  yark/channel.py
  yark/cli.py
  yark/templates/channel.html
  yark/templates/video.html
  yark/video.py
  yark/viewer.py
Labels: bug, enhancement

#67 Clean .ytdl files and add nice pathlib
  yark/channel.py
Labels: enhancement

#68 Fixed reporter types bug
  yark/channel.py
  yark/cli.py
  yark/reporter.py
  yark/video.py
Labels: bug

#56 Comment archival and viewing
  README.md
  poetry.lock
  pyproject.toml
  yark/__init__.py
  yark/channel.py
  yark/cli.py
  yark/reporter.py
  yark/templates/channel.html
  yark/video.py
  yark/viewer.py
Labels: enhancement

#76 Native playlist downloading and improved comments
  README.md
  examples/madness.py
  poetry.lock
  pyproject.toml
  yark/__init__.py
  yark/archive.py
  yark/cli.py
  yark/config.py
  yark/reporter.py
  yark/templates/archive.html
  yark/templates/base.html
  yark/templates/index.html
  yark/templates/video.html
  yark/video.py
  yark/viewer.py
Labels: bug, enhancement

#79 Added proxy support to refresh
  yark/archive.py
  yark/cli.py
  yark/config.py
Labels: enhancement

#84 Standardize archived videos to webm/mp4
  README.md
  yark/__init__.py
  yark/archive.py
  yark/converter.py
  yark/errors.py
Labels: bug, priority

#85 Viewer tabs for livestreams/shorts
  yark/templates/archive.html
  yark/templates/base.html
  yark/templates/video.html
  yark/viewer.py
Labels: enhancement, priority

#93 Add PyInstaller for 3.11 and safeguard publishing
  .gitignore
  poetry.lock
  pyproject.toml
  yark.spec
  yark/launcher.py
  yark/viewer.py
Labels: enhancement

#98 Metadata progress bars
  poetry.lock
  pyproject.toml
  yark/channel.py
Labels: enhancement

#94 Comment viewer
  yark/archiver/comment_author.py
  yark/archiver/video/comments.py
  yark/archiver/video/note.py
  yark/cli.py
  yark/templates/archive.html
  yark/templates/base.html
  yark/templates/video.html
  yark/viewer.py
Labels: enhancement

#87 Tech debt crushing and contributing file
  .gitignore
  CONTRIBUTING.md
  examples/madness.py
  poetry.lock
  pyproject.toml
  yark/__init__.py
  yark/archiver/__init__.py
  yark/archiver/archive.py
  yark/archiver/comment_author.py
  yark/archiver/config.py
  yark/archiver/converter.py
  yark/archiver/element.py
  yark/archiver/migrator.py
  yark/archiver/reporter.py
  yark/archiver/video/__init__.py
  yark/archiver/video/comments.py
  yark/archiver/video/image.py
  yark/archiver/video/note.py
  yark/archiver/video/video.py
  yark/cli.py
  yark/config.py
  yark/errors.py
  yark/logger.py
  yark/templates/archive.html
  yark/templates/base.html
  yark/templates/video.html
  yark/utils.py
  yark/video.py
  yark/viewer.py
Labels: enhancement

#101 Logging
  pyproject.toml
  yark/archiver/archive.py
  yark/archiver/config.py
  yark/archiver/converter.py
  yark/archiver/migrator.py
  yark/cli.py
  yark/errors.py
  yark/logger.py
  yark/utils.py
Labels: enhancement

#108 Project revamp integration into the GUI rewrite
  CONTRIBUTING.md
  README.md
  yark-cli/.gitignore
  yark-cli/poetry.lock
  yark-cli/pyproject.toml
  yark-cli/tests/__init__.py
  yark-cli/yark.spec
  yark-cli/yark_cli/__init__.py
  yark-cli/yark_cli/__main__.py
  yark-cli/yark_cli/archive.py
  yark-cli/yark_cli/cli.py
  yark/pyproject.toml
  yark/yark/__init__.py
  yark/yark/__main__.py
  yark/yark/archiver/comment_author.py
  yark/yark/archiver/logger.py
  yark/yark/archiver/migrator.py
  yark/yark/archiver/video/comments.py
  yark/yark/cli.py
  yark/yark/errors.py
  yark/yark/launcher.py
  yark/yark/versioning/__init__.py
  yark/yark/versioning/pypi.py
Labels: enhancement
